### ISSUE TITLE
Error running demo.py

### ISSUE THREAD

**Issue by dldaisy** [HongwenZhang/DaNet-3DHumanReconstruction#10]
Hi! I tried to run demo.py, however an error occurred as follows:

```
Traceback (most recent call last):
  File "demo.py", line 184, in <module>
    main()
  File "demo.py", line 149, in main
    global_orient=rotmat_pred[:, 0].unsqueeze(1), pose2rot=False)
  File "/home/yujun/anaconda3/envs/danet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yujun/ludai/DaNet-3DHumanReconstruction/models/smpl.py", line 29, in forward
    smpl_output = super(SMPL, self).forward(*args, **kwargs)
  File "/home/yujun/anaconda3/envs/danet/lib/python3.6/site-packages/smplx/body_models.py", line 376, in forward
    self.lbs_weights, pose2rot=pose2rot, dtype=self.dtype)
  File "/home/yujun/anaconda3/envs/danet/lib/python3.6/site-packages/smplx/lbs.py", line 179, in lbs
    v_shaped = v_template + blend_shapes(betas, shapedirs)
  File "/home/yujun/anaconda3/envs/danet/lib/python3.6/site-packages/smplx/lbs.py", line 269, in blend_shapes
    blend_shape = torch.einsum('bl,mkl->bmk', [betas, shape_disps])
  File "/home/yujun/anaconda3/envs/danet/lib/python3.6/site-packages/torch/functional.py", line 211, in einsum
    return torch._C._VariableFunctions.einsum(equation, operands)
RuntimeError: size of dimension does not match previous size, operand 1, dim 2
```
Can you give me any help regarding this issue? Thanks.

**Comment by dldaisy** [comment]
OK, figured it out myself.
I previously downloaded SMPL v1.1.0, which contains 300 PC and caused the dimension mismatch problem above. However, this code requires SMPL v1.0.0 which contains 10 PC.
Using SMPL v1.0.0 would just be fine.
