### ISSUE TITLE
Issue with dimmensions

### ISSUE THREAD

**Issue by ayushgupta9198** [HongwenZhang/DaNet-3DHumanReconstruction#13]
Hi
I am working on your model and having issue while running the code as i have all dependencies issue but still i cannot figure out the issue.

I have tried with both the SMPL models like version 1.1.0 and 1.0.0 but it still having dimensions issue

can you please help me in figuring out the issue 

ERROR:

using decomposed predictor.
input mode: IUV
/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:2693: UserWarning: Default grid_sample and affine_grid behavior will be changed to align_corners=False from 1.4.0. See the documentation of grid_sample for details.
  warnings.warn("Default grid_sample and affine_grid behavior will be changed "
/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:2751: UserWarning: Default grid_sample and affine_grid behavior will be changed to align_corners=False from 1.4.0. See the documentation of grid_sample for details.
  warnings.warn("Default grid_sample and affine_grid behavior will be changed "
Traceback (most recent call last):
  File "demo.py", line 184, in <module>
    main()
  File "demo.py", line 149, in main
    global_orient=rotmat_pred[:, 0].unsqueeze(1), pose2rot=False)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/drive/My Drive/Ayush_Gupta/3d_cloth/DaNet-3DHumanReconstruction/models/smpl.py", line 29, in forward
    smpl_output = super(SMPL, self).forward(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/smplx/body_models.py", line 376, in forward
    self.lbs_weights, pose2rot=pose2rot, dtype=self.dtype)
  File "/usr/local/lib/python3.7/dist-packages/smplx/lbs.py", line 179, in lbs
    v_shaped = v_template + blend_shapes(betas, shapedirs)
  File "/usr/local/lib/python3.7/dist-packages/smplx/lbs.py", line 265, in blend_shapes
    blend_shape = torch.einsum('bl,mkl->bmk', [betas, shape_disps])
  File "/usr/local/lib/python3.7/dist-packages/torch/functional.py", line 201, in einsum
    return torch._C._VariableFunctions.einsum(equation, operands)
RuntimeError: size of dimension does not match previous size, operand 1, dim 2

**Comment by HongwenZhang** [comment]
Hi, have you checked the version of the `smplx` package and the dimension of the shape of the SMPL model? We used the SMPL model with 10 shape PCs (not 300 PCs).
