### ISSUE TITLE
RuntimeError: faces must be contiguous?

### ISSUE THREAD

**Issue by pisceskkk** [HongwenZhang/DaNet-3DHumanReconstruction#15]
Hi, thanks for your code. But when I run `python demo.py --checkpoint=data/pretrained_model/danet_model_h36m_itw.pt --img_dir ./examples --use_opendr`, this error was reported.

> /home/pisceskkk/miniconda3/envs/danet/lib/python3.6/site-packages/torch/nn/functional.py:4004: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  "Default grid_sample and affine_grid behavior has changed "
/home/pisceskkk/miniconda3/envs/danet/lib/python3.6/site-packages/torch/nn/functional.py:4066: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  "Default grid_sample and affine_grid behavior has changed "
Traceback (most recent call last):
  File "demo.py", line 184, in <module>
    main()
  File "demo.py", line 151, in main
    render_iuv = iuv_renderer.verts2uvimg(verts_pred, camera_pred)
  File "/mnt/d/Study/DaNet-3DHumanReconstruction/utils/renderer.py", line 276, in verts2uvimg
    dist_coeffs=torch.FloatTensor([[0.] * 5]).to(verts.device))
  File "/home/pisceskkk/miniconda3/envs/danet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/pisceskkk/miniconda3/envs/danet/lib/python3.6/site-packages/neural_renderer_pytorch-1.1.3-py3.6-linux-x86_64.egg/neural_renderer/renderer.py", line 74, in forward
    return self.render_rgb(vertices, faces, textures, K, R, t, dist_coeffs, orig_size)
  File "/home/pisceskkk/miniconda3/envs/danet/lib/python3.6/site-packages/neural_renderer_pytorch-1.1.3-py3.6-linux-x86_64.egg/neural_renderer/renderer.py", line 197, in render_rgb
    self.background_color)
  File "/home/pisceskkk/miniconda3/envs/danet/lib/python3.6/site-packages/neural_renderer_pytorch-1.1.3-py3.6-linux-x86_64.egg/neural_renderer/rasterize.py", line 394, in rasterize
    faces, textures, image_size, anti_aliasing, near, far, eps, background_color, True, False, False)['rgb']
  File "/home/pisceskkk/miniconda3/envs/danet/lib/python3.6/site-packages/neural_renderer_pytorch-1.1.3-py3.6-linux-x86_64.egg/neural_renderer/rasterize.py", line 303, in rasterize_rgbad
    image_size, near, far, eps, background_color, return_rgb, return_alpha, return_depth)(*inputs)
  File "/home/pisceskkk/miniconda3/envs/danet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/pisceskkk/miniconda3/envs/danet/lib/python3.6/site-packages/neural_renderer_pytorch-1.1.3-py3.6-linux-x86_64.egg/neural_renderer/rasterize.py", line 251, in forward
    self.return_rgb, self.return_alpha, self.return_depth)
  File "/home/pisceskkk/miniconda3/envs/danet/lib/python3.6/site-packages/neural_renderer_pytorch-1.1.3-py3.6-linux-x86_64.egg/neural_renderer/rasterize.py", line 74, in forward
    face_inv_map)
  File "/home/pisceskkk/miniconda3/envs/danet/lib/python3.6/site-packages/neural_renderer_pytorch-1.1.3-py3.6-linux-x86_64.egg/neural_renderer/rasterize.py", line 166, in forward_face_index_map
    ctx.return_depth)
RuntimeError: faces must be contiguous

And my env:
Ubuntu20 in WSL2
python                    3.6.13
torch                     1.10.0+cu113
neural-renderer-pytorch   1.1.3
opendr                    0.78

**Comment by HongwenZhang** [comment]
Hi, you can try adding `. contiguous ()`  to `self.faces.to(verts.device).expand(batch_size, -1, -1)`, i.e.,
`self.faces.to(verts.device).expand(batch_size, -1, -1). contiguous ()` in [this line](https://github.com/HongwenZhang/DaNet-3DHumanReconstruction/blob/master/utils/renderer.py#L272).
